### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "32124Dsa"
}

### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "32124Dsa",
  "fullname": "User User User"
}

### Health
GET http://localhost:3000/health/
Accept: application/json


### Create Company
POST http://localhost:3000/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJmdWxsbmFtZSI6IlVzZXIgVXNlciBVc2VyIiwiaWF0IjoxNzEwNDAxNjEyLCJleHAiOjE3MTA0ODgwMTJ9.ItiE_xlRVwUvjFqPg8Z4C72vp9qGKgfjfX3CXLAVszY

{
  "company_name": "company12"
}

### View Company
GET http://localhost:3000/company/26
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJmdWxsbmFtZSI6IlVzZXIgVXNlciBVc2VyIiwiaWF0IjoxNzEwNDAxNjEyLCJleHAiOjE3MTA0ODgwMTJ9.ItiE_xlRVwUvjFqPg8Z4C72vp9qGKgfjfX3CXLAVszY

### Update Company
PUT http://localhost:3000/company/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJmdWxsbmFtZSI6IlVzZXIgVXNlciBVc2VyIiwiaWF0IjoxNzEwNDAxNjEyLCJleHAiOjE3MTA0ODgwMTJ9.ItiE_xlRVwUvjFqPg8Z4C72vp9qGKgfjfX3CXLAVszY

{
  "company_name": "company3"
}

### Delete Company
DELETE http://localhost:3000/company/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsImVtYWlsIjoidXNlckBlbWFpbC5jb20iLCJmdWxsbmFtZSI6IlVzZXIgVXNlciBVc2VyIiwiaWF0IjoxNzEwNDAxNjEyLCJleHAiOjE3MTA0ODgwMTJ9.ItiE_xlRVwUvjFqPg8Z4C72vp9qGKgfjfX3CXLAVszY

###
